apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-html-page
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: .
    repoURL: https://github.com/kvarnberg/argo_hello_app.git
    targetRevision: HEAD
  project: default